### ISSUE TITLE
index.d.ts refers to "BluetoothTranport", should be "BluetoothTransport"

### ISSUE THREAD

**Issue by cdot** [blackshadev/libdivecomputerjs#6]
I'm trying to talk to to Shearwater Teric, which uses Bluetooth, and stumbled over this typo. Change it to BluetoothTransport and it gets further.

**Comment by blackshadev** [comment]
Thanks! I will update it in the upcoming week for you when I got the time. If you already got the changes you can also create a PR and I can merge it in for you (and release it to npm ofcourse)

**Comment by cdot** [comment]
I'm not going to faff about creating a fork for such a trivial fix - quicker for you to `s/BluetoothTranport/BluetoothTransport/g` in `index.d.ts` in your existing repository.

**Comment by blackshadev** [comment]
Fixed and released as 0.7.1
